---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j
spec:
  ports:
    -
      name: frontend
      port: 7474
      targetPort: 7474
    -
      name: bolt-api
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j
  type: NodePort
