---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: neo4j-1
  name: neo4j-1
spec:
#  strategy: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: neo4j-1
  template:
    metadata:
      labels:
        name: neo4j-1
        app: neo4j
    spec:
      nodeSelector:
       failure-domain.beta.kubernetes.io/zone: eu-west-1a
      containers:
        -
          imagePullPolicy: Always
          image: neo4j:3.0.2-enterprise
          name: neo4j-1
          resources:
            limits:
              memory: "2G"
#              cpu: "100m"
          ports:
          - containerPort: 7474
            name: "http"
          - containerPort: 5001
            name: "cluster"
          - containerPort: 6001
            name: "transaction"
          env:
          - name: "NEO4J_dbms_mode"
            value: "HA"
    #      - name: NEO4J_AUTH
    #        value: "none"
          - name: NEO4J_ha_host_coordination
            value: 0.0.0.0:5001
          - name: NEO4J_ha_host_data
            value: 0.0.0.0:6001
          - name: "NEO4J_HA_ADDRESS"
            value: "0.0.0.0"
          - name: "NEO4J_ha_serverId"
            value: "1"
          - name: "NEO4J_ha_initialHosts"
            value: "neo4j-1:5001,neo4j-2:5001,neo4j-3:5001"
          volumeMounts: 
          - name: data
            mountPath: /var/lib/neo4j/data
          readinessProbe:
            exec:
             command:
              - /healthcheck.sh
            initialDelaySeconds: 100
            timeoutSeconds: 2 
          livenessProbe:
            exec:
             command:
              - /healthcheck.sh
            initialDelaySeconds: 100
            timeoutSeconds: 2 
      restartPolicy: Always
      volumes:
      - name: data
        # This AWS EBS volume must already exist.
        awsElasticBlockStore:
          volumeID: vol-b9a71a7c
          fsType: ext4
