apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: neo4j-3
  name: neo4j-3
spec:
  replicas: 1
  selector:
    name: neo4j-3
  template:
    metadata:
      labels:
        name: neo4j-3
        app: neo4j-3
    spec:
      containers:
        -
          imagePullPolicy: Always
          image: neo4j:3.0.2-enterprise
          name: neo4j-3
          resources:
            limits:
              memory: "2G"
              cpu: "500m"
          ports:
          - containerPort: 7474
            name: "http"
          - containerPort: 5001
            name: "cluster"
          - containerPort: 6001
            name: "transaction"
          env:
          - name: "NEO4J_dbms_mode"
            value: "HA"
          - name: NEO4J_AUTH
            value: "none"
          - name: NEO4J_ha_host_coordination
            value: 0.0.0.0:5001
          - name: NEO4J_ha_host_data
            value: neo4j-3:6001
#          - name: "NEO4J_HA_ADDRESS"
#            value: "0.0.0.0"
          - name: "NEO4J_ha_serverId"
            value: "3"
          - name: "NEO4J_ha_initialHosts"
            value: "neo4j-1:5001,neo4j-2:5001,neo4j-3:5001"
      restartPolicy: Always
