---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: neo4j-3
  name: neo4j-3
spec:
  ports:
    -
      name: cluster
      port: 5001
      targetPort: 5001
    -
      name: transaction
      port: 6001
      targetPort: 6001
  selector:
    name: neo4j-3
